apiVersion: apps/v1
kind: Deployment

metadata:
  name: dept-service
  namespace: department-dev

spec:
  replicas: 2

  selector:
    matchLabels:
      app: dept-service

  template:
    metadata:
      labels:
        app: dept-service

    spec:

      containers:
      - name: dept-service
        image: thannidocer/dept-service:1.0

        imagePullPolicy: Always

        ports:
        - containerPort: 8082

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8082

          failureThreshold: 30
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8082

        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8082
            
        env:
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: department-config
                key: APP_NAME

          - name: ENV
            valueFrom:
              configMapKeyRef:
                name: department-config
                key: ENV

          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: department-config
                key: LOG_LEVEL

          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: department-secret
                key: DB_USERNAME

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: department-secret
                key: DB_PASSWORD

        